# Generated by Django 4.0.4 on 2022-06-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='images/user.jpg', upload_to='profile_pics'),
        ),
    ]
